### ISSUE TITLE
feature request: do not truncate title when card is opened

### ISSUE THREAD

**Issue by takmilihsan** [Mosc/Glider#107]
If the title spans longer than two lines, ot is shown trancated with a trailing ellipsis in the card. When the story is opened, the title still isn't shown fully. The two line limit still applies.

![title truncated in opened story](https://github.com/Mosc/Glider/assets/45640333/aa54f837-5493-49e1-bae2-e6971832dc22)

![title truncated in card](https://github.com/Mosc/Glider/assets/45640333/57da138a-bab1-41cd-85d0-7d0833c17885)

**Comment by Mosc** [comment]
This is actually pretty annoying to solve, because from a developing standpoint it's very convenient that the tile has a predictable maximum height. Stuff starts breaking when that isn't the case. I made a change in a47e683e13534dc1ba0dbd50483dfc8061188047 that moves the favicon to the URL bar when opening a story. That provides more space for the title to render and should circumvent the issue for most combinations of title length and device width. That's all I can do at this point without making significant changes, so I hope that's good enough! Will be part of the next release.

Example:
<img src="https://github.com/Mosc/Glider/assets/749107/23c9f4f4-ec59-491e-90d9-57ad390338df" width=50% height=50%>

**Comment by takmilihsan** [comment]
Commendable effort and excellent app. I've downgraded to 1.8.1 and will use it until it breaks. Thanks to you, we have the choice of enjoying not just one but effectively two great app versions.

**Comment by Mosc** [comment]
Feel free to downgrade, of course, but doesn't that version have the exact same 2 line limit?

**Comment by takmilihsan** [comment]
> Feel free to downgrade, of course, but doesn't that version have the exact same 2 line limit?

It doesn't, actually.
