### ISSUE TITLE
Couple tweaks to sharing

### ISSUE THREAD

**Issue by er4hn** [Mosc/Glider#11]
I would humbly suggest making the following changes to sharing:

* Rename "Share item link" when selecting the comments thread to "Share Comments page" or something else that makes it more clear what the "item link" is. I get confused when doing this :)
* I use trello a lot to save links and I notice that you save the URL as the title. This messes with trello cards. Taking a peek at your code I am 85% sure the solution is to use the "subject" optional argument in the share package to put in the title of the link.
Thanks so much!

**Comment by Mosc** [comment]
Thanks for the suggestions! They've been implemented in 0aa079463b32796b3330e13efbca5ab178afb48a and 76f5656b0b70b75f942104a5e40eac56b3338b83, respectively. What do you think, is "Share thread link" clear enough? I don't like mentioning "comments" too much because it can technically contain more than that, like poll options.

**Comment by er4hn** [comment]
I think "Share thread link" sounds great! Thanks for making these changes.
