### ISSUE TITLE
Navigation bar appears on side on android tablet

### ISSUE THREAD

**Issue by DeepakParamkusam** [Mosc/Glider#114]
The new navigation bar in Glider 2.0 appears on the left on my Amazon Fire and takes up screen space.

OS: Fire OS 7.3.2.7 (based on Android 9.0)

![Screenshot_20231029-214308](https://github.com/Mosc/Glider/assets/21082208/c22f74d3-bb79-42d5-b9b5-b34abce81380)

**Comment by Mosc** [comment]
This follows the [Material 3 recommendations on window classes](https://m3.material.io/foundations/layout/applying-layout/window-size-classes). You mention that it takes screen space, but doesn't it actually allow for more data to be shown compared to a bottom navigation bar because horizontal space is kind of wasted?

I currently have no plans of changing this behavior.

**Comment by shuhaowu** [comment]
Looking at the recommendation, tablet at portrait mode in their screenshots all appear to have a relatively "square" aspect ratio, which gives plenty of horizontal space for content and navigation bar. When your screen ratio is 16:9 or 16:10, the left sided navigation bar takes up an excessive amount of space, while vertical space is much cheaper on a portrait tablet. It also makes the content more excessively off centered, especially since there are only three buttons that some users like myself are never going to use.

**Comment by Mosc** [comment]
The guidelines allow for some leeway in terms of which navigation methods are used, but to call this a misinterpretation is a bit... presumptuous. The current implementation is clearly one of the recommended approaches according to the specification, and also happens to closely match the example behavior of the [flutter_adaptive_scaffold](https://pub.dev/packages/flutter_adaptive_scaffold) package (with the notable exception of Glider not currently supporting a secondary body) created by the Flutter team over at Google.

**Comment by alejoar** [comment]
The left navigation is thick enough that prevents left handed navigation in tablet portrait mode. 

From the link you provided, there is no example where text is shown under the icons like Glider does. It is either icons only or icons + text to the right in landscape. If we are going to get a primary navigation sidebar in portrait mode it should at least be icons only to allow for left handed scrolling. In the flutter example they are also top aligned.

You also claim:
> You mention that it takes screen space, but doesn't it actually allow for more data to be shown compared to a bottom navigation bar because horizontal space is kind of wasted?

Why not do the same on mobile too then? Having a "taller" screen doesn't mean it's OK to eat more horizontal space.

I will also add that other than painful to see design wise, it's also an accessibility issue.

**Comment by Mosc** [comment]
I'm genuinely confused. Your tablet shows that the same _doesn't_ apply. The navigation rail exists next to the main content while still allowing the content to take all the space it needs (i.e. nothing is getting truncated). A bottom navigation bar would result in less information being displayed overall. Which is not necessarily true on phones.

Of course, it's still entirely valid for you not to like this interface. As mentioned, I'm actually quite willing to change the design, as long as it reasonably fits within the Material 3 recommendations. Thoughts on that are welcome, but calling things "awful" and claiming it's a  "misinterpretation" without being able to back that up is not really the best way to start such a discussion...

**Comment by shuhaowu** [comment]
I think the statement of the "don't have enough space" is quite subjective. For what it is worth, this UI change has caused me to stop using this app entirely.

**Comment by Mosc** [comment]
That's fair. As a direct result of this discussion I've at least changed the navigation rail on large "window size classes" to be the non-extended variety in the v2.6.0 release, but I can understand if that's not enough of a change.

**Comment by Mosc** [comment]
The latest version, v2.8.0, includes a setting to change the navigation bar or rail into a navigation drawer. I hope that is enough to resolve the concerns raised in this issue.
