### ISSUE TITLE
Sorting and searching of favorites

### ISSUE THREAD

**Issue by amalic** [Mosc/Glider#12]
Favorites seem to be sorted from old to new. Would ve great if sorting order could be switched and if favorites were searchable.

**Comment by Mosc** [comment]
When sorting by date, do you prefer sorting by date that you added the favorite, or by date that a story or comment itself was posted? I'm partial to the latter, because a) it maintains parity with the way favorites are shown on the website, and b) this is easier to achieve in a backwards-compatible way because we just need to sort the IDs in descending order.

I don't see a clean way of making favorites searchable in the current architecture. Favorites are stored as nothing more than IDs and their content isn't even loaded until visible on screen, so a local search seems unfeasible. It's somewhat possible to use the [Algolia HN API](https://hn.algolia.com/api) to construct a search combining multiple _specific_ IDs like [this](https://hn.algolia.com/api/v1/search_by_date?query=ycombinator&tags=(story,poll),(story_1,story_2,story_3)), but that has its own issues: a) that method doesn't work well for searching both stories and comments, and b) we might run into a maximum URL length limit if we have a large number of favorites.

**Comment by amalic** [comment]
I think by added date would make sense.

About srarch: At some point you load titles since you're displaying them. Simple phonetic search could be performed locally IMO.

**Comment by Mosc** [comment]
It could, but I consider a phonetic search algorithm to be out of scope for this project. Search in general is in scope, but as mentioned, posts and their titles are not loaded until they are visible on screen so it's not a trivial feature to implement in the current architecture. That makes it sit quite low on the priority list.

I'm afraid something similar can be said of sorting by added date. That requires storing dates along with the IDs, which would not be backwards-compatible, and is information that is not available on the website and would therefore cause conflict with the synchronization feature. For now I've implemented a simple sorting from new to old in ddeb145753001f5b548a047941e9a52c27381264, I hope that suffices for now.

**Comment by amalic** [comment]
Search could work with polling IMO.

Let's say you're loading chunks of 25 bookmarks. You'd need to filter them by sesrch terms. If displayed items don't fill the screen, you load the next chunk and repeat until the screen is filled up or HN Api returns zero items.

Of course it would be much more elegant if HN's Api would support such functionality.

Alternatively you could synchronize and store ID's, titles, and bookmark-dates into a local database which allows fulltext searching and maybe even phonetic searching.

**Comment by Mosc** [comment]
A simple version of this has been implemented in ec23911bba76ae76ac646f2f9dfc9ff091dcabf7 utilizing the Algolia API as much as possible. It has the limitation of only searching stories, not comments, but I'm just not willing to change the structure of the app significantly only to support that feature.
