### ISSUE TITLE
Icon color differences

### ISSUE THREAD

**Issue by Porkepix** [Mosc/Glider#124]
Glider's icon used to be yellow/orange, and is still that way on the webpages of the play store and F-droid. But during package install, and once installed the icon is now black.

Which one's the right color, and should this be fixed on the different places?
Also, it might be nice setting that icon on this repository too.

**Comment by Mosc** [comment]
The icon is supposed to be white on yellow/orange (unless using the themed icons feature on newer Android versions).

Can you check if the same occurs in v2.2.0, available [here](https://github.com/Mosc/Glider/releases/tag/v2.2.0) or whenever it has finished processing at Google Play or F-Droid? Otherwise please share a screenshot, as I'm unable to reproduce the issue on my configurations.

**Comment by Mosc** [comment]
Good to hear. ff4040c2a20384a69ffe5c6d2da5a7efb3296409 probably fixed it. The PNG optimizer messed up initially.

As for the repository icon, I don't think I can actually set one. The icon shown is just the user's profile picture.
