### ISSUE TITLE
Launching Glider from a link on Android doesn't work anymore in v2.2.0

### ISSUE THREAD

**Issue by Gabr-F** [Mosc/Glider#135]
Launching Glider from a link (view intent), of all of

https://news.ycombinator.com/item
https://news.ycombinator.com/user
https://news.ycombinator.com/submit

kinds of urls, in the F-Droid v2.2.0 version always results in simply a completely gray screen.

It used to work in (F-Droid) v2.1.0, I used it for days opening many links from an HackerNews' Telegram channel.

I'm actually perplexed that it did work in v2.1.0 because I can't find any code to handle intents even in that version (but everything I know about flutter, dart etc. I learned this afternoon).

It seems very likely that the culprit is the huge 1c5c896 .

Opening links was, unfortunately, in practice the only use case I had for Glider, since it's lighter than a browser and I could stay logged in into it (while I in my browser I use a feature that deletes all cookies at every launch).

**Comment by Mosc** [comment]
This confused me for a bit, but it turns out that this is a regression due to a recent bug in the `go_router` package, which erroneously strips query parameters under certain circumstances. Which is obviously bad for https://news.ycombinator.com/item?id=1 style URLs. #131 should fix this, and will of course be included in upcoming releases.

For reference, the fact that deeplinking works at all is because `flutter_deeplinking_enabled` is defined in the `AndroidManifest,xml`. That causes the URL to be sent to the router in Flutter, `go_router` in our case, which then matches up deeplinks to internal route paths.

**Comment by Gabr-F** [comment]
Oh ok great!!

Yes I did find out about go_router eventually
