### ISSUE TITLE
Option to copy links

### ISSUE THREAD

**Issue by mrmotallebi** [Mosc/Glider#18]
First off, thanks for the cool app!

A minor tweak if possible, can you add the option to copy the links to both the article ("link") and the conversation thread on HN. Right now sharing is possible but copy to clipboard doesn't appear in the share menu.

Thanks!

**Comment by Mosc** [comment]
This is actually interesting, because I thought the clipboard copy function is just an option that's always present in the share menu. Turns out there's lots of reports on the internet of people (suddenly) missing that option, part of which can apparently be tracked down to not having Google Drive installed. I guess I'll need to add it in the app directly, but I'm not sure in what form because I don't want to litter the long-press menu with too many options. Could be a sub menu. As a workaround, consider an external "share to clipboard" app, such as the open-source [Share to Clipboard](https://github.com/tengusw/share_to_clipboard).

**Comment by Mosc** [comment]
Fixed as part of 5254eab63b213c7e52df1a8b59254a501e509824.
