### ISSUE TITLE
Feature Request: Option to turn off thumbnails

### ISSUE THREAD

**Issue by digg33** [Mosc/Glider#21]
Most posts in HN are links to blog posts, documentation or webpages unlike Reddit, which has also has image and video links. It would be nice to be able to disable thumbnails in Glider as I find that it does not add much to the experience (webpages = tiny text + lots of white in the thumbnail).

Thanks,
digg33

**Comment by Mosc** [comment]
I understand where you're coming from, and I agree the thumbnail often doesn't provide the most useful info. It does however double as a convenient touch target to launch the article rather than having to swipe on the tile, and on most devices I don't think the empty spaced created by hiding the thumbnail would be used for anything else. Would you say the main reason for wanting to hide it is to reduce clutter? In any case, this is not an option I'm willing to introduce _at this point_ because the increased maintenance cost associated with extra configuration options is not worth it to me.

**Comment by digg33** [comment]
Hi Mosc,

Thank you for considering the feature request. I fully understand and agree with not wanting to introduce any additional configuration unless absolutely needed and I can see how minimalism from a configuration standpoint is part of Glider's appeal. Reducing visual clutter by homogenising the appearance of each post was indeed the idea behind disabling thumbnails, as you've identified. With that in mind, have you considered perhaps using an arrow or a button instead of thumbnails as a convenient touch target? Here's how the 'reddit is fun' app does it:

![image](https://user-images.githubusercontent.com/58906128/121334335-18080700-c909-11eb-9be0-510761720455.png)

Thanks,
digg33

**Comment by Mosc** [comment]
This has been implemented as part of fb0b81ef755d671feb5e647d22424103b0fc0033 and e4c0ce5515bd2f44fe6ca570d8d10d5848a141a5. Toggles for showing or hiding several story list UI elements (the shortened URL appended to the title, the thumbnail, and the metadata row) have been added to the Theme menu option, which has been renamed to the more general sounding Appearance. No replacement touch target for the thumbnail spot has been added for now, as I think those wanting to hide the thumbnail will generally appreciate a more compact rendering. I'll admit the minimalist look after hiding various elements has a certain appeal.

I want to do a bit more testing before releasing it into the wild, but if everything goes well it should be part of the next version of the app.

<img alt="" width="328px" src="https://user-images.githubusercontent.com/749107/125991779-18ee3bb8-2885-408f-b9b8-4424abdbcda6.png">
