### ISSUE TITLE
Long press to select comment text?

### ISSUE THREAD

**Issue by ddarfantasy** [Mosc/Glider#22]
In many circumstances I don't want to copy the whole comment text, I only want to copy some sections. But there's already a long-press menu, is there a way to implement it?

**Comment by Mosc** [comment]
This would be a nice feature, but it's not feasible to implement right now. Glider relies on flutter_widget_from_html to render the (subset of) HTML that can be present in Hacker News comments. That package currently does not provide a way to make text selectable (https://github.com/daohoangson/flutter_widget_from_html/issues/102) because it requires issue https://github.com/flutter/flutter/issues/38474 in the Flutter framework to be solved. I'm willing to work on this once the mentioned requirements have been fulfilled.

**Comment by Mosc** [comment]
Not blocked anymore since version 0.8.3 of `flutter_widget_from_html_core`. We can consider implementing this now.

**Comment by Mosc** [comment]
Small correction: this is still blocked. `flutter_widget_from_html` supports selectable text, but `flutter_widget_from_html_core` (which we use) doesn't yet. Also, as you mentioned, long-press is already used for accessing more options, so suggestions on how to make the user interaction sensible are welcome.

**Comment by Mosc** [comment]
After trying out the mentioned selectable text function in `flutter_widget_from_html` I realized the user experience just wasn't going to be good enough with in-place text selection, so I went the different, simple option of adding a menu option that spawns a dialog with selectable but unformatted text. The result of that is 73921da24c9fe53196b6e8cf0b16a5fb3c251623. Will be available in the next release.
