### ISSUE TITLE
Open links externally (using the browser, not custom tabs)

### ISSUE THREAD

**Issue by laurentlbm** [Mosc/Glider#23]
Basically, the opposite of #9 😉
Could it be a setting?

**Comment by Victor239** [comment]
From the custom tab it only takes a second to open it as browser tab though.

**Comment by laurentlbm** [comment]
And that's an extra step every time. 
I dislike custom tabs and don't find any value in them. I can't switch back and forth between the article and the comments. Plus, the options are limited, e.g. I can't share from the custom tab.

**Comment by Mosc** [comment]
I'll admit easy switching between article and comments sounds like a good argument for opening links in a browser. Sharing from a custom tab is a special case, because Glider [does specifically request](https://github.com/Mosc/Glider/blob/master/lib/utils/url_util.dart#L43) the custom tab browser to show a share menu. Chrome does show one, Firefox does not unfortunately.

I might turn this into a setting later on when the app matures, but right now I'm choosing to focus my limited time on other features because I don't want an increase in settings to make maintenance more complex.

**Comment by ellidi** [comment]
This is the reason I am going with another app. It's a shame because I like everything else about the app.

**Comment by Mosc** [comment]
Setting added in 6c24a5032e1245c6d6852526198678f0c2a15b8f. Will be part of the next release, although I'm not sure when that will appear on the Play Store, given that Google is making my life difficult over user-generated content policies.

**Comment by ellidi** [comment]
> 
> 
> Setting added in [6c24a50](https://github.com/Mosc/Glider/commit/6c24a5032e1245c6d6852526198678f0c2a15b8f). Will be part of the next release, although I'm not sure when that will appear on the Play Store, given that Google is making my life difficult over user-generated content policies.

F-Droid is the way to go anyway ;)

**Comment by Mosc** [comment]
Definitely. :grinning:
