### ISSUE TITLE
A option to view users thread

### ISSUE THREAD

**Issue by KotUW** [Mosc/Glider#27]
If possible is there  a way to show threads that are available by https://news.ycombinator.com/threads?id=user 

Maybe in the menu where we select askhn, showhn, e.tc.. add a option for users threads

**Comment by Mosc** [comment]
This is kind of already available by tapping on a username, right? It's not exactly the same, as a user's comments and submissions are shown in a flat list rather than the threaded view that the website renders. However, such a rendering is a bit unfeasible in Glider because of limitations in the [Hacker News API](https://github.com/HackerNews/API) that the app uses. Were you unaware of the app's user profile page, or is your request specifically about threaded views?

**Comment by Not3vil** [comment]
![Screenshot_20210717-143445](https://user-images.githubusercontent.com/46974369/126032119-4b6ed67d-f9f0-4894-a80b-0084f012f3b1.jpg)

I wasn't aware, cause account tab never loads for me. I thought that's for multiple accounts or something.

**Comment by Not3vil** [comment]
I reinstalled and it works now. It's good enough in its current state through if it show threades response in the account tab it will be better especially your response to a comment to your response are both shown as new cards. Close this if you want

**Comment by Mosc** [comment]
Oh, I had not realized you were trying to view _your own_ profile. Yes, the quickest way to do that is visit the account page. Not sure why it errored out before, but I'm glad a reinstall fixed it. I wouldn't be against implementing threaded comments, but as mentioned, I don't see a clean way to do that with the current Hacker News API.
