### ISSUE TITLE
App showing nothing.

### ISSUE THREAD

**Issue by dhishkyaon** [Mosc/Glider#28]
![Screenshot_20210806-205153_1](https://user-images.githubusercontent.com/88529066/128533765-e8150575-e06f-4798-9d26-bcc5dc36ccc3.png)

**Comment by Mosc** [comment]
Not my finest work. Someday I'll add more detailed error messages.

For now, can you tell me if this error occurs on both a Wi-Fi and a mobile data connection? I'm wondering if there's something special about your network. Can you access the URL https://hacker-news.firebaseio.com/v0/topstories.json on your phone normally? Is the search or catch up functionality also broken, which uses a different API?

**Comment by hellyeahmfs** [comment]
> Not my finest work. Someday I'll add more detailed error messages.
> 
> For now, can you tell me if this error occurs on both a Wi-Fi and a mobile data connection? I'm wondering if there's something special about your network. Can you access the URL https://hacker-news.firebaseio.com/v0/topstories.json on your phone normally? Is the search or catch up functionality also broken, which uses a different API?

Sorry my bad. I am using NextDNS and its blocking the app content and this URL. But why is this happening?

**Comment by Mosc** [comment]
Honestly I'm not sure why. I activated NextDNS for a bit and could not get it to block the URL through normal means. Only enabling a rigorous blocklist like [No Google](https://github.com/nickspaargaren/no-google) would stop Glider form working, which is because the official Hacker News API is hosted on Firebase, a Google platform. Maybe there's some other blocklist that trips on the word "hacker" in the URL. You should be able to check under the Logs tab on https://my.nextdns.io/ what is causing the URL to be blocked.

**Comment by hellyeahmfs** [comment]
*Blocked by NoTracker Track List*
I added this domain to allowlist. Now its working. Thanks 🙂
