### ISSUE TITLE
Unable to open links on Android

### ISSUE THREAD

**Issue by aniketpant** [Mosc/Glider#3]
I stumbled upon Glider a couple of months ago and love the app! Sometime in the November/December update, the ability to open links stopped working. As of now, none of the links in the post or the comments open anything for me.

Unsure about what's the best way to report a bug but happy to try and provide more information.

**Comment by Mosc** [comment]
Thanks for the report! Do you happen to run Android 11? I think it has to do with the new [package visibility](https://developer.android.com/about/versions/11/privacy/package-visibility). Looks like I forgot to update to read the release notes properly before updating to the new API. Will be fixed in the next release.

**Comment by aniketpant** [comment]
@Mosc Yes that must be the reason. My update to Android 11 must have coincided with one of the releases and that probably led to the confusion on my end.

**Comment by Mosc** [comment]
Should be fixed in 8f660c93487044ddc8d93fc97a0591ce477e88e1. Let me know if you still experience issues in the next release.
