### ISSUE TITLE
Feature request: text size

### ISSUE THREAD

**Issue by mrondr** [Mosc/Glider#40]
Not much to add to the title: I think many of us would benefit from the possibility to pick text size.

Awesome app btw ;-)

**Comment by Mosc** [comment]
Hey. I have to say I'm not convinced of the need for this. Modern OSs offer extensive options for customizing text size, and this app uses very standard text styles that should appropriately scale with those settings. Is there any reason you'd want disproportionally small or large text sizes in Glider? I'm also curious if you'd like to mainly adjust the post title size, comment text size, or both!

**Comment by mrondr** [comment]
I agree with you on the fact that the app scales well. This said, the main reason for this request is conveniecy. Different apps have different font styles and size, and respond to different needs hence different reading habits. That extra text-adjusting knob is a life saver. Also try to think of the complementary case: text size is fine everywhere but in this app: one would have to adjust the system setting to match the app needs and run throught all n-1 apps to reset text size.

**Comment by Mosc** [comment]
Right. I'm not one to use different densities for different apps, but I guess everyone's usage is different! That said, I'm not sure I want to commit to this feature right now, so I'm going to let it sit for a bit.

**Comment by sortebill** [comment]
I'd also want this feature implemented. I use some settings on my phone that makes the text in this particular app a tad bit too small, if I adjust it up a little everything else kinda becomes a little wacky so instead of having to adapt my phone settings to comfortably use this app I'd love it if it was possible to adjust the text size within it. It also depends a little on the amount of text on screen, my sms app shows the text a tad bit bigger than in Glider so a setting for this would be very much appreciated.

**Comment by Mosc** [comment]
By popular demand, this has been implemented in bc62b8ed5b152b56e49997f2ff757a3817bb03f1. Should be part of the next release.

A few things to note:

- The setting impacts all the text in the app proportionally.
- The setting acts on top of the system's font size setting instead of overriding it, so setting the system's font size to large and the app's to large as well will make text look extra large.
- The possible sizes are "small", "medium" and "large", which correspond to multipliers of 0.85, 1 and 1.15 respectively. These values match the values used for the global Android font size setting, but are not set in stone and may be adjusted in a later release.

**Comment by PolGZ** [comment]
I'm sorry to post on a closed issue, but on v. 2.8.0 from FDroid I'm not able to see these text option under settings. I can only pick the font type/family, but not the supposedly available size of it.

What am I missing? 

I really like to have my system UI in a somewhat normal/not-big setting, but having heavily text-based apps where you only read and read text, to have a bigger font size so I don't force my eyes as  much and if the article is long even keep the font a bit more far from my eyes than regular phone use case.

Running on Android 14 on a Pixel 5 device (CalyxOS)
