### ISSUE TITLE
Show total number of child replies together/instead_of first level child 

### ISSUE THREAD

**Issue by s3wall** [Mosc/Glider#41]
Show total number of child replies instead of first level child in collapsed comments thread.
It seems like major commenting platform like reddit and news.ycombinator use the total number.

Would be great, either switch to total number, adding both number (dept=1 and total number) or adding an option to show also the total.

**Comment by Mosc** [comment]
That does make more sense. The reason Glider currently only displays the number of direct children is because that's all that is returned from the [API](https://github.com/HackerNews/API). We already recursively load the entire comment chain so I'm sure the total number of a comment's descendants could be determined at the same time, but it would require some additional logic compared to the current implementation.

**Comment by Mosc** [comment]
Implemented in 415b9417186edc85ad4f779ca64ef2838c907e26.
