### ISSUE TITLE
Bug: Glider for HN doesn't respect the system font setrings.

### ISSUE THREAD

**Issue by vanessa-vd98** [Mosc/Glider#49]
Hi,

Thank you very much for developing Glider for Hacker News. I use it everyday. It is one of the most used app on my Galaxy.

But the app doesn't respect my system font. On Galaxy devices, Samsung allows the user to change the font. I use MT Neue Haas Grotesk typeface on all my other apps but Glider for HN
is still using the default typeface.

Please fix this when you have time. Cheers :)

**Comment by Mosc** [comment]
Wouldn't mind implementing this, but it turns out it's not that easy to do using Flutter. See the open issue [here](https://github.com/flutter/flutter/issues/48381). Some possible solutions are discussed [on StackOverflow](https://stackoverflow.com/questions/51913485/how-to-use-the-devices-default-font-in-flutter) but I feel that they are too hacky to consider.

**Comment by Mosc** [comment]
This is still blocked, but various opened duplicate issues requested a font selection setting as a workaround. I've implemented that in 874af9b2afa4fdeffe2bd53db5c1cd97dba6198a, and included several of the mentioned fonts plus a few more: Fira Sans, IBM Plex Sans, Inter, Noto Sans, Open Sans and Roboto. Unfortunately I can only reasonably include fonts available on Google Fonts, and Helvetica/Neue Haas Grotesk is not in that list.

Let me know if there's a font that you're missing, but for now I'll close this issue until the Flutter framework allows using the system's font.

**Comment by DwainZwerg** [comment]
@Mosc There is also a plugin https://github.com/re7gog/android_system_font
