### ISSUE TITLE
Feature request: disable animations

### ISSUE THREAD

**Issue by An4cl3t0** [Mosc/Glider#6]
Hi, I think the animation of the drop down menu is somewhat too slow, could the app respect the system setting for the velocity of animations or set an option to disable it? 
Thanks again

**Comment by Mosc** [comment]
Which drop down menu specifically are we talking about?

Unfortunately, it does not seem to be possible to hook into the system animation settings because [Android does not expose this in its API](https://github.com/flutter/flutter/issues/10101#issuecomment-398940831). That said, Glider does respect the "Remove animations" setting in Android's Accessibility menu. Is that too drastic for your use case? I am open to changing animation durations, but would prefer not to add a setting for it within Glider because I strongly value keeping the UI uncluttered.

**Comment by Mosc** [comment]
I see. That one's set to a fixed [300 millisecond](https://github.com/flutter/flutter/blob/c5a4b4029c/packages/flutter/lib/src/material/popup_menu.dart#L30) opening and closing animation by the Flutter framework. I'm surprised you're using it often enough to notice its (slow) animation! I suppose theoretically one could read Android's [ANIMATOR_DURATION_SCALE](https://developer.android.com/reference/android/provider/Settings.Global#ANIMATOR_DURATION_SCALE) setting via a [Flutter method channel](https://flutter.dev/docs/development/platform-integration/platform-channels) during startup and using that value to set a [timeDilation](https://api.flutter.dev/flutter/scheduler/timeDilation.html), but that feels too hacky for me to consider at this moment. Closing this for now.
