### ISSUE TITLE
Error when posting, even if it posted correctly.

### ISSUE THREAD

**Issue by FarisZR** [Mosc/Glider#67]
When posting a story using Glider, it always shows that there was an error, even though the post is fine and shows up normally on HN.

**Comment by Mosc** [comment]
Hah, I guess the "experimental" warning on that page is appropriate. Not a function that I test often.

Looks like the redirect location that Glider checks is inaccurate. I think it did work at some point, so it may have changed server-side. Fixed in f38bece79c355cd549382ed9ebe3dad6d23fc962.

Thanks!
