### ISSUE TITLE
Remember collapsed comments 

### ISSUE THREAD

**Issue by Victor239** [Mosc/Glider#8]
It would be great if when opening a discussion page for a second time it would remember which comments you collapsed when last viewing the page.

**Comment by Mosc** [comment]
Sounds reasonable. Would remembering collapsed statuses within a session be enough, or would you like this data to survive app restarts? I'm leaning towards the former because I don't really want the app to store an ever-growing list of IDs for this feature forever, but I'm curious to hear your use case.

**Comment by Victor239** [comment]
I'd like it to remember a few days minimum, but not more than a month. I might review the same discussion over a few days or week if it's a hot or interesting topic, but very rarely a few weeks later. 

I wouldn't think it would take up much storage compared to say the cache for other apps I use like YouTube, Reddit and web browsers.

**Comment by Mosc** [comment]
Yeah, the storage space itself is not an issue, I'm just thinking about the performance impact of having to check the collapsed status of every comment in a thread based on a perpetually growing list of IDs.

**Comment by Victor239** [comment]
If it were deleted after a few days - month as suggested though it wouldn't be perpetually growing though would it? Would probably store 100 threads at most.

**Comment by Mosc** [comment]
Right. That's at the cost of complexity though, you'd have to store a date along with the ID and figure out when to trim the list. For now I've kept the implementation simple in 495a298aa240f0d85bcf4fedec80ad3e58573a94, which should be fine for the vast majority of users.

Because the collapsed statuses now have to be read from storage instead of memory upon a restart, this data is loaded asynchronously, which usually causes saved collapses' animations to trigger after loading items rather than them immediately starting in a collapsed state. Looks a bit funky, but it works.
