### ISSUE TITLE
Open links using browser Custom Tabs

### ISSUE THREAD

**Issue by Victor239** [Mosc/Glider#9]
I've been using the (abandoned) app [Hews](https://github.com/leavjenn/Hews) to read HN and one feature I really liked from it is the ability to select a browser (in my case Firefox) with which to open the link in as an overlay (AKA [Custom Tabs](https://developer.chrome.com/docs/android/custom-tabs/overview/)), rather than opening it in the full web browser. It would be great to have this feature here as well.

**Comment by Mosc** [comment]
Implemented in f4d6b8cfd40e822428ac594ae62b6348a5509d3c. The thing about Custom Tabs is that I'd still expect a YouTube link to be opened by the YouTube app, rather than in an in-app browser. Luckily Google has provided some sample native code for this use case in its [best practices](https://developer.chrome.com/docs/android/custom-tabs/best-practices/#let-native-applications-handle-the-content). Handling a URL is therefore now done according to the following priority list:

1. Let platform handle opening URL in a non-browser app, if available.
2. Open URL in a Custom Tab, if available.
3. Let platform handle opening URL.

No prefetching is performed for now.
