### ISSUE TITLE
Consider making voting and starring more convenient

### ISSUE THREAD

**Issue by mon-jai** [Mosc/Glider#95]
Voting and starring discussions/comments are actions I frequently perform. It's cumbersome and time-consuming to long-press an item every time I want to vote or star it (sometimes I do both in the same time).

Could you consider adding back quick action gestures or, alternatively, adding additional buttons for voting and starring?

**Comment by Mosc** [comment]
Will definitely consider. I've experimented with adding buttons in the story/comment tiles before but did not find a satisfactory look yet that provided big enough hitboxes but didn't occupy a large amount of space. Reintroducing gestures is still on the table, albeit in opt-in form.

**Comment by Mosc** [comment]
Added a setting for "action buttons" in 1df97557feb5bd8fc8defd5cadef6d0331e1589e, rolling out as part of v2.1.0, that replace the existing favorite icon and upvote count in the metadata row with always visible, interactive buttons. I'm closing this because it meets the requirements you've set, but feel free to provide feedback on the implementation.

**Comment by mon-jai** [comment]
I have a small suggestion. It would make more sense to place the author on the left and other metadata/buttons on the right, like this.

```
Author                        Favourite Upvotes Comments Time
```

Additionally, have you made a decision regarding adding the Roboto font to the app? (#94)

**Comment by Mosc** [comment]
I can see where you're coming from, but I tried this out a while ago and it doesn't feel right. The amount of upvotes is an important piece of information that needs to be in a predictable spot in order to be easily scannable. Having it at the proposed position means it's constantly in a different position, depending on the variable width of the time component.

As for the fonts, no, not yet, but please keep discussion about issues on-topic. :)
